
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 15 18:16:48 CEST 2019
//----------------------------------------------------

package cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final int UMINUS = 12;
  public static final int NUMBER = 15;
  public static final int MAX = 8;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int ID = 16;
  public static final int COMMA = 11;
  public static final int error = 1;
  public static final int RPAREN = 14;
  public static final int SQRT = 9;
  public static final int TIMES = 5;
  public static final int LPAREN = 13;
  public static final int EXP = 10;
  public static final int MIN = 7;
}

