
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 25 16:36:44 CEST 2019
//----------------------------------------------------

package nl.pim16aap2.jcalculator.cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 13;
  public static final int PLUS = 3;
  public static final int RPAREN = 16;
  public static final int SEMI = 2;
  public static final int SQRT = 9;
  public static final int LPAREN = 15;
  public static final int ID = 18;
  public static final int EXP = 10;
  public static final int COMMA = 12;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int ABS = 11;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int MIN = 7;
  public static final int MAX = 8;
  public static final int UMINUS = 14;
}

