name: Publish release and deploy to Maven Central

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release Version. e.g., 1.10.1
        required: true
        type: string
      nextDevVersion:
        description: Next Dev Version. e.g., 1.10.2-SNAPSHOT
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-release-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      MAVEN_GPG_FINGERPRINT: 6C063BAA00065DFED08D7CD6B21CB73DBBF60FE5
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Configure Git identity + sign commits & tags
        run: |
          git config --global user.name  "PimvanderLoos"
          git config --global user.email "3114723+PimvanderLoos@users.noreply.github.com"
          git config --global user.signingkey ${MAVEN_GPG_FINGERPRINT}
          git config --global commit.gpgsign true
          git config --global tag.gpgSign true

      - name: Set up JDK 8 + GPG + Central creds
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 8
          cache: maven
          gpg-private-key: ${{ secrets.MAVEN_GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN

      - name: Prepare release (commits + tag)
        run: |
          mvn --batch-mode --show-version --no-transfer-progress \
            -DreleaseVersion='${{ inputs.releaseVersion }}' \
            -DdevelopmentVersion='${{ inputs.nextDevVersion }}' \
            -DsignTag=true \
            -Darguments="-Psign -Dgpg.keyname=${MAVEN_GPG_FINGERPRINT}" \
            release:prepare

      - name: Upload build artifacts (JARs + .asc)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: jcalculator-${{ github.sha }}
          if-no-files-found: error
          path: |
            target/JCalculator-*.jar*

      - name: Perform release (builds tag, signs, deploys to Central)
        run: |
          mvn --batch-mode --show-version --no-transfer-progress \
            -Darguments="-Psign -Dgpg.keyname=${MAVEN_GPG_FINGERPRINT}" \
            release:perform

      - name: Deploy Javadoc to GitHub Pages (optional)
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: gh-pages
          folder: target/reports/apidocs
          target-folder: /

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          tag_name: v${{ inputs.releaseVersion }}
          target_commitish: ${{ github.sha }}
          files: |
            target/JCalculator-${{ inputs.releaseVersion }}.jar*
